In [4]:
import numpy as np

In [47]:
# creating an array and sorting elements

arr = np.array([2,8,6,9,1,0,4,3])

print(np.sort(arr))

[0 1 2 3 4 6 8 9]


# Math operations

In [48]:
# creating two 1-D arrays 

arr1 = np.array([13,14,15,16,17,18,19,20,21,22])

arr2 = np.array([23,24,25,26,27,28,29,30,31,32])

In [49]:
# addition operation
print(arr1 + arr2)

[36 38 40 42 44 46 48 50 52 54]


In [50]:
# subtraction operation
print(arr1 - arr2)

[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]


In [51]:
# multiply operation
print(arr1 * arr2)

[299 336 375 416 459 504 551 600 651 704]


In [52]:
# divide operation
print(arr1 / arr2)

[0.56521739 0.58333333 0.6        0.61538462 0.62962963 0.64285714
 0.65517241 0.66666667 0.67741935 0.6875    ]


In [53]:
# creating two 2-D arrays

arr1 = np.array([[2,8,6],[7,9,3]])

arr2 = np.array([[7,9,3],[2,8,6]])

In [54]:
# add operation
print(arr1 + arr2)

[[ 9 17  9]
 [ 9 17  9]]


In [55]:
# sub operation
print(arr1 - arr2)

[[-5 -1  3]
 [ 5  1 -3]]


In [56]:
# multi operation
print(arr1 * arr2)

[[14 72 18]
 [14 72 18]]


In [57]:
# div operation
print(arr1 / arr2)

[[0.28571429 0.88888889 2.        ]
 [3.5        1.125      0.5       ]]


In [58]:
# creating an arry and finding sqrt by using for loop

x = np.array([25,28,31,36,40,43,45,49,])

for i in x:
    print(np.sqrt(i))

5.0
5.291502622129181
5.5677643628300215
6.0
6.324555320336759
6.557438524302
6.708203932499369
7.0


# Slicing arrays

In [86]:
# creating 1-D arry and applying slicing method

arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# Positive slicing
# only start
print(arr[1:])

[30 24 50 38 73  3 37 67 35  9 21 48 76 23 13]


In [87]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# start and stop
print(arr[2:9])

[24 50 38 73  3 37 67]


In [88]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# start,stop and step
print(arr[3:10:2])

[50 73 37 35]


In [89]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# only stop
print(arr[:12])

[20 30 24 50 38 73  3 37 67 35  9 21]


In [90]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# only step
print(arr[::3])

[20 50  3 35 48 13]


In [91]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

# stop and step
print(arr[:12:2])

[20 24 38  3 67  9]


In [92]:
# negative slicing

arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

print(arr[-10:-3])

[ 3 37 67 35  9 21 48]


In [93]:
arr = np.array([20,30,24,50,38,73,3,37,67,35,9,21,48,76,23,13])

print(arr[-12:-2:2])

[38  3 67  9 48]


In [98]:
# slicing for 2-D arrays

arr1 = np.array([[10,20,30,40,50,60],[70,80,90,100,150,200]])

print(arr1[1,2:5])

[ 90 100 150]


In [100]:
arr1 = np.array([[10,20,30,40,50,60],[70,80,90,100,150,200]])

print(arr1[0,1:5])

[20 30 40 50]


In [105]:
arr1 = np.array([[10,20,30,40,50,60],[70,80,90,100,150,200]])

print(arr1[0:2,2])

[30 90]


In [106]:
arr1 = np.array([[10,20,30,40,50,60],[70,80,90,100,150,200]])

print(arr1[0:2,5])

[ 60 200]


In [107]:
arr1 = np.array([[10,20,30,40,50,60],[70,80,90,100,150,200]])

print(arr1[0:2,1:5])

[[ 20  30  40  50]
 [ 80  90 100 150]]
