# Numpy

Define numpy ?

Numpy is a Python library.

Numpy is used for working with arrays.

Numpy stands for Numerical Python.

Numpy was created in 2005 by Travis Oliphant.It is an open source.

What is an array ? 

In Python they are containers which are able to store more than one item at the same time.The array is a process of memory allocation.  

In [1]:
# installing numpy library by using Exclamatory mark(!)

!pip install numpy

In [2]:
# importing numpy library by using import function

import numpy as np       # np is the alias of numpy

In [3]:
# ceating an array
# 0-dimension array              # ndim function is used to find no.of dimensional array it is.

arr = np.array(24)

print(arr)
print(arr.ndim)

24
0


In [4]:
# 5 examples of array   
# 1-dimension array             # dtype function refers to which type of data is using.

arr1 = np.array([2,8,6],dtype = float)

print(arr1)
print(arr1.ndim)

[2. 8. 6.]
1


In [5]:
# 2-dimension array

arr2 = np.array([(9,6,8),(4,7,2)])

print(arr2)
print(arr2.ndim)

[[9 6 8]
 [4 7 2]]
2


In [6]:
# 2-dimension array

arr3 = np.array([(98,14,56,24),(90,67,31,85)],dtype = float)

print(arr3)
print(arr3.ndim)

[[98. 14. 56. 24.]
 [90. 67. 31. 85.]]
2


In [7]:
# 3-dimension array

arr4 = np.array([[(74,87,23),(45,45,12)],[(2,8,6),(3,7,5)]])

print(arr4)
print(arr4.ndim)

[[[74 87 23]
  [45 45 12]]

 [[ 2  8  6]
  [ 3  7  5]]]
3


In [8]:
# 3-dimension array

arr5 = np.array([[(12,13),(25,26)],[(57,58),(78,79)]],dtype = float)

print(arr5)
print(arr5.ndim)

[[[12. 13.]
  [25. 26.]]

 [[57. 58.]
  [78. 79.]]]
3


In [9]:
# Numpy functions
# creating zeros matrix(1*1)

mat1 = np.zeros([3],dtype = int)

print(mat1)
print(mat1.ndim)

[0 0 0]
1


In [10]:
# creating zeros matrix(2*2)

mat2 = np.zeros([2,2],dtype = int)

print(mat2)
print(mat2.ndim)

[[0 0]
 [0 0]]
2


In [11]:
# creating zeros matrix(3*3)

mat3 = np.zeros([2,3,3],dtype = int)

print(mat3)
print(mat3.ndim)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3


In [12]:
# creating ones matrix(1*1)

mat1 = np.ones([3],dtype = int)

print(mat1)

[1 1 1]


In [13]:
# creating ones matrix(2*2)

mat2 = np.ones([2,2],dtype = int)

print(mat2)

[[1 1]
 [1 1]]


In [14]:
# creating ones matrix(3*3)

mat3 = np.ones([2,3,3],dtype = int)

print(mat3)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [16]:
# creating identity matrix      # diagonals are 1 and others are 0.

arr = np.eye(2,2,dtype = int)

print(arr)

[[1 0]
 [0 1]]


In [18]:
# creating identity matrix(6*6)

arr1 = np.eye(6,6,dtype = int)

print(arr1)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [23]:
# creating a matrix with filling of user number

matr1 = np.full([2,2],4)

print(matr1)

[[4 4]
 [4 4]]


In [24]:
matr2 = np.full([2,2],[4,7])

print(matr2)

[[4 7]
 [4 7]]


In [27]:
matr3 = np.full([4,4],[2,8,6,9])

print(matr3)

[[2 8 6 9]
 [2 8 6 9]
 [2 8 6 9]
 [2 8 6 9]]


In [29]:
# creating a range of an array

arr = np.arange(2,20,3)              # (start,stop,step)

print(arr)

[ 2  5  8 11 14 17]


In [31]:
# creating evenly spaced values 

arr1 = np.linspace(28,69,10)         # (start,stop,no.of values)

print(arr1)

[28.         32.55555556 37.11111111 41.66666667 46.22222222 50.77777778
 55.33333333 59.88888889 64.44444444 69.        ]
