In [2]:
import numpy as np

In [12]:
# creating an array with random numbers

arr = np.random.random([4,3])

print(arr)

[[0.27754198 0.05581486 0.11974452]
 [0.25672759 0.57531027 0.14458381]
 [0.75553784 0.1344641  0.01694832]
 [0.57924624 0.72105848 0.647095  ]]


In [20]:
# finding shape of an array(rows,columns)

arr1 = np.array([(2,6,9),(4,7,1)])

print(arr1.shape)

(2, 3)


In [23]:
# creating 5*5 array 

arr2 = np.array([(12,13,14,15,16),(22,23,24,25,26),(32,33,34,35,36),(42,43,44,45,46),(52,53,54,55,56)])

# finding shape
print(arr2.shape)

(5, 5)


In [24]:
# finding no.of elements in an array

arr2 = np.array([(12,13,14,15,16),(22,23,24,25,26),(32,33,34,35,36),(42,43,44,45,46),(52,53,54,55,56)])

print(arr2.size)

25


In [30]:
# finding no.of rows by using len.

arr2 = np.array([(12,13,14,15,16),(22,23,24,25,26),(32,33,34,35,36),(42,43,44,45,46),(52,53,54,55,56)])

len(arr2)

5

In [36]:
# accessing elements from an array by using index number.

arr2 = np.array([(12,13,14,15,16),(22,23,24,25,26),(32,33,34,35,36),(42,43,44,45,46),(52,53,54,55,56)])

arr2[0,3]

15

In [37]:
arr2[3,1]

43

In [38]:
arr2[4,4]

56

In [43]:
# accessing elements from 3-D array

arr3 = np.array([[[101,102,103,104],[105,106,107,108]],
                 [[111,112,113,114],[115,116,117,118]],
                 [[121,122,123,124],[125,126,127,128]],
                 [[131,132,133,134],[135,136,137,138]]])

arr3[0,0,2]

103

In [44]:
# accessing elements from 3-D array

arr3 = np.array([[[101,102,103,104],[105,106,107,108]],
                 [[111,112,113,114],[115,116,117,118]],
                 [[121,122,123,124],[125,126,127,128]],
                 [[131,132,133,134],[135,136,137,138]]])

arr3[1,0,3]

114

In [47]:
# accessing elements from 3-D array

arr3 = np.array([[[101,102,103,104],[105,106,107,108]],
                 [[111,112,113,114],[115,116,117,118]],
                 [[121,122,123,124],[125,126,127,128]],
                 [[131,132,133,134],[135,136,137,138]]])

arr3[2,1,0]

125

In [48]:
# accessing elements from 3-D array

arr3 = np.array([[[101,102,103,104],[105,106,107,108]],
                 [[111,112,113,114],[115,116,117,118]],
                 [[121,122,123,124],[125,126,127,128]],
                 [[131,132,133,134],[135,136,137,138]]])

arr3[3,1,3]

138

In [53]:
# creating 1-D array and using function reshape().

arr4 = np.array([21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36])

arr4.reshape(4,4)

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [65]:
# creating 1-D array with 120 numbers and reshaping into 2-D array

arr4 = np.array([100,105,110,115,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250,100,105,110,115,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250,100,105,110,115,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250,100,105,110,115,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200,205,210,215,220,225,230,235,240,245,250])

arr4.reshape(12,10)

array([[100, 105, 110, 115, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [100, 105, 110, 115, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [100, 105, 110, 115, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250],
       [100, 105, 110, 115, 125, 130, 135, 140, 145, 150],
       [155, 160, 165, 170, 175, 180, 185, 190, 195, 200],
       [205, 210, 215, 220, 225, 230, 235, 240, 245, 250]])

In [66]:
# reshaping into 3-D array

arr4.reshape(6,4,5)

array([[[100, 105, 110, 115, 125],
        [130, 135, 140, 145, 150],
        [155, 160, 165, 170, 175],
        [180, 185, 190, 195, 200]],

       [[205, 210, 215, 220, 225],
        [230, 235, 240, 245, 250],
        [100, 105, 110, 115, 125],
        [130, 135, 140, 145, 150]],

       [[155, 160, 165, 170, 175],
        [180, 185, 190, 195, 200],
        [205, 210, 215, 220, 225],
        [230, 235, 240, 245, 250]],

       [[100, 105, 110, 115, 125],
        [130, 135, 140, 145, 150],
        [155, 160, 165, 170, 175],
        [180, 185, 190, 195, 200]],

       [[205, 210, 215, 220, 225],
        [230, 235, 240, 245, 250],
        [100, 105, 110, 115, 125],
        [130, 135, 140, 145, 150]],

       [[155, 160, 165, 170, 175],
        [180, 185, 190, 195, 200],
        [205, 210, 215, 220, 225],
        [230, 235, 240, 245, 250]]])

In [68]:
# creating an array and copying that array

arr = np.array([11,22,33,44,55,66,77,88,99])
z = arr.copy()
arr[4] = 1000

print(arr)
print(z)

[  11   22   33   44 1000   66   77   88   99]
[11 22 33 44 55 66 77 88 99]


In [69]:
# creating an array and viewing that array

arr = np.array([10,20,30,40,50,60,70,80,90])
c = arr.view()
arr[7] = 999

print(arr)
print(c)

[ 10  20  30  40  50  60  70 999  90]
[ 10  20  30  40  50  60  70 999  90]


# Data types

Numpy has some extra data types,and refer to data types with one character,like i for integers, u for unsigned integers etc.

In [1]:
# Below list of all data types in Numpy and characters used to represent them.

# i = integer
# b = boolean
# u = unsigned integer
# c = complex float
# f = float
# m = timedelta
# M = datetime
# O = object
# S = string
# U = unicode string

In [3]:
# creating an array with data type string

arr = np.array([2,5,7,8,9,4,1,6],dtype = 'S')

print(arr)
print(arr.dtype)

[b'2' b'5' b'7' b'8' b'9' b'4' b'1' b'6']
|S1


In [8]:
# creating an array with data type int

arr1 = np.array([1.2,2.6,7.3,8.4,9.4,4.7,2.8],dtype = 'i')

print(arr1)
print(arr1.dtype)

[1 2 7 8 9 4 2]
int32


In [9]:
# creating an array with data type float

arr2 = np.array([2,5,7,8,9,4,1,6],dtype = 'f')

print(arr2)
print(arr2.dtype)

[2. 5. 7. 8. 9. 4. 1. 6.]
float32


In [10]:
# converting data type on existing arrays using astype() method.
# creating an array and converting into int data type.
arr3 = np.array([1.3,4.6,3.7,8.5,9.7,2.8,8.5])

arr3.astype('i')

array([1, 4, 3, 8, 9, 2, 8], dtype=int32)

In [11]:
# creating an array and converting boolean data type.

arr4 = np.array([1,5,8,2,0,3,0,4,-3,-5,5j])

arr4.astype(bool)

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True])